# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProductDialog(object):
    def setupUi(self, ProductDialog):
        ProductDialog.setObjectName("ProductDialog")
        ProductDialog.resize(800, 305)
        ProductDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name_line_edit = QtWidgets.QLineEdit(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_line_edit.setFont(font)
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.symbol_line_edit = QtWidgets.QLineEdit(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.symbol_line_edit.setFont(font)
        self.symbol_line_edit.setObjectName("symbol_line_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.symbol_line_edit)
        self.unit_line_edit = QtWidgets.QLineEdit(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.unit_line_edit.setFont(font)
        self.unit_line_edit.setObjectName("unit_line_edit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.unit_line_edit)
        self.unit_net_price_line_edit = QtWidgets.QLineEdit(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.unit_net_price_line_edit.setFont(font)
        self.unit_net_price_line_edit.setObjectName("unit_net_price_line_edit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unit_net_price_line_edit)
        self.vat_line_edit = QtWidgets.QLineEdit(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vat_line_edit.setFont(font)
        self.vat_line_edit.setObjectName("vat_line_edit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.vat_line_edit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yes_radio_btn = QtWidgets.QRadioButton(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.yes_radio_btn.setFont(font)
        self.yes_radio_btn.setObjectName("yes_radio_btn")
        self.verticalLayout_2.addWidget(self.yes_radio_btn)
        self.no_radio_btn = QtWidgets.QRadioButton(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.no_radio_btn.setFont(font)
        self.no_radio_btn.setChecked(True)
        self.no_radio_btn.setObjectName("no_radio_btn")
        self.verticalLayout_2.addWidget(self.no_radio_btn)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProductDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProductDialog)
        self.buttonBox.rejected.connect(ProductDialog.reject)
        self.buttonBox.accepted.connect(ProductDialog._validate_input)
        self.buttonBox.accepted.connect(ProductDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(ProductDialog)

    def retranslateUi(self, ProductDialog):
        _translate = QtCore.QCoreApplication.translate
        ProductDialog.setWindowTitle(_translate("ProductDialog", "Dialog"))
        self.label.setText(_translate("ProductDialog", "Nazwa"))
        self.label_2.setText(_translate("ProductDialog", "Symbol"))
        self.label_3.setText(_translate("ProductDialog", "Jednostka"))
        self.label_4.setText(_translate("ProductDialog", "Cena\n"
"jednostkowa\n"
"netto [zł]"))
        self.label_5.setText(_translate("ProductDialog", "Stawka\n"
"VAT [%]"))
        self.label_6.setText(_translate("ProductDialog", "Rozliczanie\n"
"comiesięczne"))
        self.yes_radio_btn.setText(_translate("ProductDialog", "Tak"))
        self.no_radio_btn.setText(_translate("ProductDialog", "Nie"))

